export type CountryCode = {
  name: string;
  dial_code: string;
  value: string;
  flag: string;
}

export const countryCodes: CountryCode[] = [
  { name: 'Afghanistan', dial_code: '+93', value: 'AF', flag: '🇦🇫' },
  { name: 'Albania', dial_code: '+355', value: 'AL', flag: '🇦🇱' },
  { name: 'Algeria', dial_code: '+213', value: 'DZ', flag: '🇩🇿' },
  { name: 'Andorra', dial_code: '+376', value: 'AD', flag: '🇦🇩' },
  { name: 'Angola', dial_code: '+244', value: 'AO', flag: '🇦🇴' },
  { name: 'Argentina', dial_code: '+54', value: 'AR', flag: '🇦🇷' },
  { name: 'Armenia', dial_code: '+374', value: 'AM', flag: '🇦🇲' },
  { name: 'Australia', dial_code: '+61', value: 'AU', flag: '🇦🇺' },
  { name: 'Austria', dial_code: '+43', value: 'AT', flag: '🇦🇹' },
  { name: 'Azerbaijan', dial_code: '+994', value: 'AZ', flag: '🇦🇿' },
  { name: 'Bahamas', dial_code: '+1-242', value: 'BS', flag: '🇧🇸' },
  { name: 'Bahrain', dial_code: '+973', value: 'BH', flag: '🇧🇭' },
  { name: 'Bangladesh', dial_code: '+880', value: 'BD', flag: '🇧🇩' },
  { name: 'Belarus', dial_code: '+375', value: 'BY', flag: '🇧🇾' },
  { name: 'Belgium', dial_code: '+32', value: 'BE', flag: '🇧🇪' },
  { name: 'Belize', dial_code: '+501', value: 'BZ', flag: '🇧🇿' },
  { name: 'Benin', dial_code: '+229', value: 'BJ', flag: '🇧🇯' },
  { name: 'Bolivia', dial_code: '+591', value: 'BO', flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', dial_code: '+387', value: 'BA', flag: '🇧🇦' },
  { name: 'Botswana', dial_code: '+267', value: 'BW', flag: '🇧🇼' },
  { name: 'Brazil', dial_code: '+55', value: 'BR', flag: '🇧🇷' },
  { name: 'Brunei Darussalam', dial_code: '+673', value: 'BN', flag: '🇧🇳' },
  { name: 'Bulgaria', dial_code: '+359', value: 'BG', flag: '🇧🇬' },
  { name: 'Burkina Faso', dial_code: '+226', value: 'BF', flag: '🇧🇫' },
  { name: 'Cambodia', dial_code: '+855', value: 'KH', flag: '🇰🇭' },
  { name: 'Cameroon', dial_code: '+237', value: 'CM', flag: '🇨🇲' },
  { name: 'Canada', dial_code: '+1', value: 'CA', flag: '🇨🇦' },
  { name: 'Central African Republic', dial_code: '+236', value: 'CF', flag: '🇨🇫' },
  { name: 'Chad', dial_code: '+235', value: 'TD', flag: '🇹🇩' },
  { name: 'Chile', dial_code: '+56', value: 'CL', flag: '🇨🇱' },
  { name: 'China', dial_code: '+86', value: 'CN', flag: '🇨🇳' },
  { name: 'Colombia', dial_code: '+57', value: 'CO', flag: '🇨🇴' },
  { name: 'Congo', dial_code: '+242', value: 'CG', flag: '🇨🇬' },
  { name: 'Costa Rica', dial_code: '+506', value: 'CR', flag: '🇨🇷' },
  { name: 'Croatia', dial_code: '+385', value: 'HR', flag: '🇭🇷' },
  { name: 'Cuba', dial_code: '+53', value: 'CU', flag: '🇨🇺' },
  { name: 'Cyprus', dial_code: '+357', value: 'CY', flag: '🇨🇾' },
  { name: 'Czech Republic', dial_code: '+420', value: 'CZ', flag: '🇨🇿' },
  { name: 'Denmark', dial_code: '+45', value: 'DK', flag: '🇩🇰' },
  { name: 'Djibouti', dial_code: '+253', value: 'DJ', flag: '🇩🇯' },
  { name: 'Dominican Republic', dial_code: '+1-809', value: 'DO', flag: '🇩🇴' },
  { name: 'Ecuador', dial_code: '+593', value: 'EC', flag: '🇪🇨' },
  { name: 'Egypt', dial_code: '+20', value: 'EG', flag: '🇪🇬' },
  { name: 'El Salvador', dial_code: '+503', value: 'SV', flag: '🇸🇻' },
  { name: 'Estonia', dial_code: '+372', value: 'EE', flag: '🇪🇪' },
  { name: 'Ethiopia', dial_code: '+251', value: 'ET', flag: '🇪🇹' },
  { name: 'Finland', dial_code: '+358', value: 'FI', flag: '🇫🇮' },
  { name: 'France', dial_code: '+33', value: 'FR', flag: '🇫🇷' },
  { name: 'Gabon', dial_code: '+241', value: 'GA', flag: '🇬🇦' },
  { name: 'Gambia', dial_code: '+220', value: 'GM', flag: '🇬🇲' },
  { name: 'Georgia', dial_code: '+995', value: 'GE', flag: '🇬🇪' },
  { name: 'Germany', dial_code: '+49', value: 'DE', flag: '🇩🇪' },
  { name: 'Ghana', dial_code: '+233', value: 'GH', flag: '🇬🇭' },
  { name: 'Greece', dial_code: '+30', value: 'GR', flag: '🇬🇷' },
  { name: 'Guatemala', dial_code: '+502', value: 'GT', flag: '🇬🇹' },
  { name: 'Honduras', dial_code: '+504', value: 'HN', flag: '🇭🇳' },
  { name: 'Hong Kong', dial_code: '+852', value: 'HK', flag: '🇭🇰' },
  { name: 'Hungary', dial_code: '+36', value: 'HU', flag: '🇭🇺' },
  { name: 'Iceland', dial_code: '+354', value: 'IS', flag: '🇮🇸' },
  { name: 'India', dial_code: '+91', value: 'IN', flag: '🇮🇳' },
  { name: 'Indonesia', dial_code: '+62', value: 'ID', flag: '🇮🇩' },
  { name: 'Iran', dial_code: '+98', value: 'IR', flag: '🇮🇷' },
  { name: 'Iraq', dial_code: '+964', value: 'IQ', flag: '🇮🇶' },
  { name: 'Ireland', dial_code: '+353', value: 'IE', flag: '🇮🇪' },
  { name: 'Israel', dial_code: '+972', value: 'IL', flag: '🇮🇱' },
  { name: 'Italy', dial_code: '+39', value: 'IT', flag: '🇮🇹' },
  { name: 'Jamaica', dial_code: '+1-876', value: 'JM', flag: '🇯🇲' },
  { name: 'Japan', dial_code: '+81', value: 'JP', flag: '🇯🇵' },
  { name: 'Jordan', dial_code: '+962', value: 'JO', flag: '🇯🇴' },
  { name: 'Kazakhstan', dial_code: '+7', value: 'KZ', flag: '🇰🇿' },
  { name: 'Kenya', dial_code: '+254', value: 'KE', flag: '🇰🇪' },
  { name: 'Kuwait', dial_code: '+965', value: 'KW', flag: '🇰🇼' },
  { name: 'Latvia', dial_code: '+371', value: 'LV', flag: '🇱🇻' },
  { name: 'Lebanon', dial_code: '+961', value: 'LB', flag: '🇱🇧' },
  { name: 'Libya', dial_code: '+218', value: 'LY', flag: '🇱🇾' },
  { name: 'Lithuania', dial_code: '+370', value: 'LT', flag: '🇱🇹' },
  { name: 'Luxembourg', dial_code: '+352', value: 'LU', flag: '🇱🇺' },
  { name: 'Malaysia', dial_code: '+60', value: 'MY', flag: '🇲🇾' },
  { name: 'Maldives', dial_code: '+960', value: 'MV', flag: '🇲🇻' },
  { name: 'Mali', dial_code: '+223', value: 'ML', flag: '🇲🇱' },
  { name: 'Malta', dial_code: '+356', value: 'MT', flag: '🇲🇹' },
  { name: 'Mexico', dial_code: '+52', value: 'MX', flag: '🇲🇽' },
  { name: 'Monaco', dial_code: '+377', value: 'MC', flag: '🇲🇨' },
  { name: 'Mongolia', dial_code: '+976', value: 'MN', flag: '🇲🇳' },
  { name: 'Montenegro', dial_code: '+382', value: 'ME', flag: '🇲🇪' },
  { name: 'Morocco', dial_code: '+212', value: 'MA', flag: '🇲🇦' },
  { name: 'Myanmar', dial_code: '+95', value: 'MM', flag: '🇲🇲' },
  { name: 'Nepal', dial_code: '+977', value: 'NP', flag: '🇳🇵' },
  { name: 'Netherlands', dial_code: '+31', value: 'NL', flag: '🇳🇱' },
  { name: 'New Zealand', dial_code: '+64', value: 'NZ', flag: '🇳🇿' },
  { name: 'Nicaragua', dial_code: '+505', value: 'NI', flag: '🇳🇮' },
  { name: 'Niger', dial_code: '+227', value: 'NE', flag: '🇳🇪' },
  { name: 'Nigeria', dial_code: '+234', value: 'NG', flag: '🇳🇬' },
  { name: 'North Korea', dial_code: '+850', value: 'KP', flag: '🇰🇵' },
  { name: 'Norway', dial_code: '+47', value: 'NO', flag: '🇳🇴' },
  { name: 'Oman', dial_code: '+968', value: 'OM', flag: '🇴🇲' },
  { name: 'Pakistan', dial_code: '+92', value: 'PK', flag: '🇵🇰' },
  { name: 'Panama', dial_code: '+507', value: 'PA', flag: '🇵🇦' },
  { name: 'Paraguay', dial_code: '+595', value: 'PY', flag: '🇵🇾' },
  { name: 'Peru', dial_code: '+51', value: 'PE', flag: '🇵🇪' },
  { name: 'Philippines', dial_code: '+63', value: 'PH', flag: '🇵🇭' },
  { name: 'Poland', dial_code: '+48', value: 'PL', flag: '🇵🇱' },
  { name: 'Portugal', dial_code: '+351', value: 'PT', flag: '🇵🇹' },
  { name: 'Puerto Rico', dial_code: '+1-787', value: 'PR', flag: '🇵🇷' },
  { name: 'Qatar', dial_code: '+974', value: 'QA', flag: '🇶🇦' },
  { name: 'Romania', dial_code: '+40', value: 'RO', flag: '🇷🇴' },
  { name: 'Russia', dial_code: '+7', value: 'RU', flag: '🇷🇺' },
  { name: 'Saudi Arabia', dial_code: '+966', value: 'SA', flag: '🇸🇦' },
  { name: 'Senegal', dial_code: '+221', value: 'SN', flag: '🇸🇳' },
  { name: 'Serbia', dial_code: '+381', value: 'RS', flag: '🇷🇸' },
  { name: 'Singapore', dial_code: '+65', value: 'SG', flag: '🇸🇬' },
  { name: 'Slovakia', dial_code: '+421', value: 'SK', flag: '🇸🇰' },
  { name: 'Slovenia', dial_code: '+386', value: 'SI', flag: '🇸🇮' },
  { name: 'Somalia', dial_code: '+252', value: 'SO', flag: '🇸🇴' },
  { name: 'South Africa', dial_code: '+27', value: 'ZA', flag: '🇿🇦' },
  { name: 'South Korea', dial_code: '+82', value: 'KR', flag: '🇰🇷' },
  { name: 'Spain', dial_code: '+34', value: 'ES', flag: '🇪🇸' },
  { name: 'Sri Lanka', dial_code: '+94', value: 'LK', flag: '🇱🇰' },
  { name: 'Sudan', dial_code: '+249', value: 'SD', flag: '🇸🇩' },
  { name: 'Sweden', dial_code: '+46', value: 'SE', flag: '🇸🇪' },
  { name: 'Switzerland', dial_code: '+41', value: 'CH', flag: '🇨🇭' },
  { name: 'Syria', dial_code: '+963', value: 'SY', flag: '🇸🇾' },
  { name: 'Taiwan', dial_code: '+886', value: 'TW', flag: '🇹🇼' },
  { name: 'Tanzania', dial_code: '+255', value: 'TZ', flag: '🇹🇿' },
  { name: 'Thailand', dial_code: '+66', value: 'TH', flag: '🇹🇭' },
  { name: 'Tunisia', dial_code: '+216', value: 'TN', flag: '🇹🇳' },
  { name: 'Turkey', dial_code: '+90', value: 'TR', flag: '🇹🇷' },
  { name: 'Uganda', dial_code: '+256', value: 'UG', flag: '🇺🇬' },
  { name: 'Ukraine', dial_code: '+380', value: 'UA', flag: '🇺🇦' },
  { name: 'United Arab Emirates', dial_code: '+971', value: 'AE', flag: '🇦🇪' },
  { name: 'United Kingdom', dial_code: '+44', value: 'GB', flag: '🇬🇧' },
  { name: 'United States', dial_code: '+1', value: 'US', flag: '🇺🇸' },
  { name: 'Uruguay', dial_code: '+598', value: 'UY', flag: '🇺🇾' },
  { name: 'Uzbekistan', dial_code: '+998', value: 'UZ', flag: '🇺🇿' },
  { name: 'Venezuela', dial_code: '+58', value: 'VE', flag: '🇻🇪' },
  { name: 'Vietnam', dial_code: '+84', value: 'VN', flag: '🇻🇳' },
  { name: 'Yemen', dial_code: '+967', value: 'YE', flag: '🇾🇪' },
  { name: 'Zambia', dial_code: '+260', value: 'ZM', flag: '🇿🇲' },
  { name: 'Zimbabwe', dial_code: '+263', value: 'ZW', flag: '🇿🇼' },
];
